### ISSUE TITLE
[META] Main mapset list

### ISSUE THREAD

**Issue by mifu666** [Mythotic-Tinker-Station/lexicon#7]
Subtasks will be available for each mapset when its time to add it.

- [x] 1994 Tune-Up Project = 1994tu.wad
- [ ] 3 Hours in Agony series = 3hafinal.wad, 3ha2.wad, 3ha3.wad
- [ ] 32in24-14
- [ ] 5 Rooms = 5room.wad
- [ ] 50 Shades of Doom = 50shades.wad, 50shades_mpfix.wad
- [x] Ancient Aliens
- [x] BTSX 1 = btsx_e1_099i9.wad
- [ ] BTSX 2 = btsx_e2a.wad, btsx_e2b.wad, btsxe2-palette.wad, btsxe2-cd-liquidpatch.v2.wad
- [ ] Bloodstain = bstain.wad
- [x] Chainworm = chainworm.wad
- [x] Circle of Caina = dbp_02.wad
- [x] Claustrophobia 1024
- [x] Claustrophobia 1024 2: The Mystery of Too Many Maps
- [x] Community Chest 1 = cchest.wad
- [x] Community Chest 2 = cchest2.wad
- [x] Community Chest 3 = cchest3fix.wad
- [x] Community Chest 4 = cchest4.wad
- [x] Congestion 1024
- [x] Dark Encounters
- [ ] Dimensions of the boomed = dotb_rc1.wad
- [x] Doom 2 Redux
- [ ] Doom 2 Reloaded = d2reload.wad
- [x] Doom 2 The Way iD Did = d2twid.wad
- [x] Doom Core = dcv.wad (Under Doom core Trilogy) 
- [ ] Doomworld Megawad Project 2015 = dmp15.wad
- [ ] Doomworld Megawad Project 2016 = dmp2016v2.wad
- [ ] Doomworld Megawad Project 2017 = dmp2017-final.wad
- [x] Epic 1
- [x] Epic 2 = epic2fix.wad
- [x] Estranged = estrangd.wad
- [ ] Eviltech
- [ ] Extermination day (when its done)
- [x] Forest Swords = dbp_03.wad
- [ ] Freudian Slipgate = freudslp.wad
- [x] Going Down = gd.wad
- [ ] Hell Awakened = hellawakened.wad
- [x] Hellbound = hellbnd-v2.wad, hellboundcomplex.v3b.wad(will need to look into fix soon)
- [x] Hellcore = hc20.wad, hc20-coopfix.pk3
- [ ] Hellebarde = hellbrd.wad
- [ ] Herian 2 = herian2-v2.wad, herian2-complexpatch.v1.wad
- [x] Interception
- [ ] Japanese Community Compilation Project = jpcp.wad, jpcp_coopfix.wad
- [ ] Jenesis = jenesis.wad, jenefix.wad
- [x] Khorus's Speedy Shit
- [ ] Lunatic = lunatic.wad (this has a complex patch if you need it from me or it might be on tspg. (lunatic-complexpatch.v1.wad)
- [x] Maps of Chaos
- [x] Mayhem wads = mayhem12.wad, mayhem2013.wad mayhem16.wad, mayhem17.wad, mayhem2048.wad, mayhem1500v1-50.wad
- [x] Monuments of Mars = dbp_01.wad
- [ ] Moonblood = moonbld.wad
- [ ] Mutiny = mutiny.wad
- [ ] Necrophobia = necropia2010.wad
- [ ] New Doom Community Pack 2 = ndcp2.wad
- [x] Nova I
- [ ] Nova II = nova2.wad
- [ ] Resurgence = resurge.wad
- [ ] Space Wars = spacwars.wad
- [ ] Sparta 2 - Project Vesuvious = s2pv.wad
- [x] Stardate 20x6 = stardate20x6.wad
- [x] Stardate 20x7 = sd20x7.wad
- [ ] Suitcase of Gor = suitcase-v2.wad
- [x] Sunlust = sunlust.wad (What a bitch)
- [ ] TNT Re-Evilution = tntr.wad
- [ ] Tangerine nightmare = tn.wad
- [x] UAC Ultra = uacultra.wad, uacultravfix.wad
- [x] Unholy Realms = ur_final.wad
- [ ] Urania = urania.wad
- [x] Valiant (vanilla/non-vanilla) = valve.wad valient.wad - i think?
- [ ] War DSV = war_3.wad
- [x] Zone 300
- [x] Zones of Fear

## SLAUGHTER WADS

- [ ] Between demon claws = bdc.wad i think?
- [x] Combat Shock 1 and 2 (already in pk3)
- [ ] Coopbuildm
- [x] Destination Unknown
- [x] Deus Vult 1
- [x] Deus Vult 2
- [x] Drown in Blood = dib28a.wad dibsnd.wad
- [ ] Good Morning Phobos = gmp.wad
- [ ] Harvest X = harvestx.wad
- [ ] Invasion UAC
- [x] New Gothic Movement 1 (ngmvmt1.wad)
- [x] New Gothic Movement 2 (ngmvmt2.wad)
- [x] Pizza Time = pizzas.wad
- [ ] Rush = rush.wad
- [ ] Slaughterfest 2011 = sf2011.wad
- [x] Slaughterfest 2012 = sf2012_final.wad
- [x] Slaughterfest 2013 = sf3_c.wad
- [x] Sunder = sunder.wad
- [ ] Survive in hell = sihr2fix-noblood.wad, sihr2patch.wad
- [x] Swift Death = swideath.wad
- [x] Swim with the Whales
- [x] Chillax

## SINGLE MAPS

- [ ] Aeternum
- [ ] Awakening
- [ ] Bad Religion
- [ ] Foursite
- [ ] Fuel Devourer
- [ ] Hanging Gardens
- [ ] Holy Hell
- [ ] Jade Earth
- [ ] My Soul Trapped in a WIN98 PC
- [x] The Eye
- [ ] The Great Ubran Battle
- [x] The Spire 1
- [x] The Spire 2
- [ ] XXXI CyberSky

**Comment by Tribeam** [comment]
I modified the formatting and added checkboxes.

**Comment by svcino** [comment]
add Neodoom newworld and newworld2
